version: "3.9"
services:
  ledger:
    build: .
    platform: linux/amd64
    environment:
      ANOMA_LEDGER__ETHEREUM__MODE: EventsEndpoint
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:26657:26657'
      - '127.0.0.1:3030:3030'
  adhoc:
    build: .
    platform: linux/amd64
    environment:
      &anoma_env
      ANOMA_NETWORK_CONFIGS_SERVER: http://ledger:8123
      ANOMA_LEDGER_ADDRESS: ledger:26657
      ANOMA_ETHEREUM_EVENTS_ENDPOINT: http://ledger:3030/eth_events
    command:
      - /bin/bash
      - -c
      - |
        export ANOMA_CHAIN_ID="$$(cat chain-id)"
        tail -F /dev/null
  testrunner:
    build: .
    platform: linux/amd64
    environment: *anoma_env
    command:
      - /bin/bash
      - -c
      - |
        export ANOMA_CHAIN_ID="$$(cat chain-id)"
        tests/e2e_submit_fake_transfer && \
        tests/attempt_modify_wdai_supply
    depends_on:
      - ledger
