version: "3.9"
services:
  ledger:
    build: .
    environment:
      - ANOMA_LEDGER__ETHEREUM__MODE=EventsEndpoint
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:26657:26657'
      - '127.0.0.1:3030:3030'
  adhoc:
    build: .
    environment:
      &anoma_env
      ANOMA_NETWORK_CONFIGS_SERVER: http://ledger:8123
      ANOMA_LEDGER_ADDRESS: ledger:26657
    command:
      - /bin/bash
      - -c
      - |
        tail -F /dev/null
    depends_on:
      - ledger
  testrunner:
    build: .
    environment: *anoma_env
    command:
      - /bin/bash
      - -c
      - |
        tests/attempt_modify_wdai_supply && \
        tests/submit_wdai_transfer
    depends_on:
      - ledger
